#!/bin/bash
begin=2
end=40000
command="/root/pppoe-middleware/"

while [ $begin -lt $end ]
do
	if [ -f /proc/${begin}/cmdline ]
	then
		cmd=`cat /proc/${begin}/cmdline`
		echo "$cmd" |grep -q "$command"
		if [ $? -eq 0 ]
		then
			echo $cmd
			kill -9 $begin
		fi
	fi
	begin=`expr $begin + 1`
done


