#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH
export today=`date '+%Y-%m-%d'`
LOGDEVICE=$6
REALDEVICE=$1

id=`cat /proc/$$/status | grep "PPid" | cut -d':' -f2`

/sbin/tc qdisc del dev $1 root
/sbin/tc qdisc del dev $1 ingress

php /etc/ppp/speed-limit/speedLimit.php $1 $2 >> /var/log/pppoe_project/$today 
php /etc/ppp/login-logout/login.php $2 $id >> /var/log/pppoe_project/$today 
php /etc/ppp/login-logout/authregister.php $1 $2 $id >> /var/log/pppoe_project/$today 
