#!/bin/bash
count=2010
end=2019
eth=em2
while [ $count -lt $end ] 
do
        vconfig add ${eth} ${count}
        vconfig set_flag ${eth}.${count} 1 1
        ifconfig ${eth}.${count} up
        count=`expr $count + 1`
done


count=2160
end=2179
eth=em2
while [ $count -lt $end ] 
do
        vconfig add ${eth} ${count}
        vconfig set_flag ${eth}.${count} 1 1
        ifconfig ${eth}.${count} up
        count=`expr $count + 1`
done


pppoe-server -I em2.2160 -N 62 -L 10.0.0.1 -R 10.18.4.1 -S pppoe-113 -k
pppoe-server -I em2.2161 -N 62 -L 10.0.0.1 -R 10.18.4.65 -S pppoe-113 -k
pppoe-server -I em2.2162 -N 62 -L 10.0.0.1 -R 10.18.4.129 -S pppoe-113 -k
pppoe-server -I em2.2163 -N 62 -L 10.0.0.1 -R 10.18.4.193 -S pppoe-113 -k
pppoe-server -I em2.2164 -N 62 -L 10.0.0.1 -R 10.18.5.1 -S pppoe-113 -k
pppoe-server -I em2.2165 -N 62 -L 10.0.0.1 -R 10.18.5.65 -S pppoe-113 -k
pppoe-server -I em2.2166 -N 62 -L 10.0.0.1 -R 10.18.5.129 -S pppoe-113 -k
pppoe-server -I em2.2167 -N 62 -L 10.0.0.1 -R 10.18.5.193 -S pppoe-113 -k
pppoe-server -I em2.2168 -N 62 -L 10.0.0.1 -R 10.18.6.1 -S pppoe-113 -k
pppoe-server -I em2.2169 -N 62 -L 10.0.0.1 -R 10.18.6.65 -S pppoe-113 -k
pppoe-server -I em2.2170 -N 62 -L 10.0.0.1 -R 10.18.7.1 -S pppoe-113 -k
pppoe-server -I em2.2171 -N 62 -L 10.0.0.1 -R 10.18.7.65 -S pppoe-113 -k
pppoe-server -I em2.2172 -N 62 -L 10.0.0.1 -R 10.18.7.129 -S pppoe-113 -k
pppoe-server -I em2.2173 -N 62 -L 10.0.0.1 -R 10.18.7.193 -S pppoe-113 -k
pppoe-server -I em2.2174 -N 62 -L 10.0.0.1 -R 10.18.8.1 -S pppoe-113 -k
pppoe-server -I em2.2175 -N 62 -L 10.0.0.1 -R 10.18.8.65 -S pppoe-113 -k
pppoe-server -I em2.2176 -N 62 -L 10.0.0.1 -R 10.18.8.129 -S pppoe-113 -k
pppoe-server -I em2.2177 -N 62 -L 10.0.0.1 -R 10.18.8.193 -S pppoe-113 -k
pppoe-server -I em2.2178 -N 62 -L 10.0.0.1 -R 10.18.9.1 -S pppoe-113 -k
pppoe-server -I em2.2179 -N 62 -L 10.0.0.1 -R 10.18.9.65 -S pppoe-113 -k

